### ISSUE TITLE
I don’t understand how it works, or how it should work

### ISSUE THREAD

**Issue by mrranger** [DoKM/SteamHourBooster#1]
`Steam HourBooster By DoKM91AS
Version = 1.2.8

loaded AES
loaded RSA Private Key
RSA public Key exists
connected as id 45

/app/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

TypeError: Cannot read property 'forEach' of undefined
    at Query.<anonymous> (/app/build/app.js:575:25)
    at Query.<anonymous> (/app/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/app/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:88:28)`

tables of type s_accounts are not being created yet
Could you please give sql so that it can be imported

**Comment by DoKM** [comment]
the tables get created by laravel, the website part of it in the frontend folder.
should just migrate it either automatically or via artisan, i havent touched this in ages

**Comment by mrranger** [comment]
I'll take a look, just a very interesting project

**Comment by mrranger** [comment]
I've been struggling with this for the second day, and I don't understand what he wants


C:\Windows\system32>docker exec php php artisan migrate:fresh

   Illuminate\Database\QueryException

  SQLSTATE[HY000] [2002] Connection refused (SQL: SHOW FULL TABLES WHERE table_type = 'BASE TABLE')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:671
    667|         // If an exception occurs when attempting to run a query, we'll format the error
    668|         // message to include the bindings with SQL, which will make this exception a
    669|         // lot more helpful to the developer instead of just the database's errors.
    670|         catch (Exception $e) {
  > 671|             throw new QueryException(
    672|                 $query, $this->prepareBindings($bindings), $e
    673|             );
    674|         }
    675|

      +46 vendor frames
  47  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by mrranger** [comment]
Happened !

.env

DB_HOST=mysql

1.) docker exec php php artisan config:cache
2.) docker exec php php artisan migrate:fresh
